In [ ]:
# Loading the dataset in - since it is so large, it must be done using batch processing

import pandas as pd
import kagglehub


csv_path = kagglehub.dataset_download(
    "sobhanmoosavi/us-accidents",
    path="US_Accidents_March23.csv",
)

batch_size = 10000
batches = []
batch_num = 0

for batch in pd.read_csv(csv_path, chunksize=batch_size, low_memory=False):
    batches.append(batch)
    batch_num += 1
    if batch_num % 20 == 0:
        print(f"Processed {batch_num * batch_size} rows")

df = pd.concat(batches, ignore_index=True)
print(df.shape)

/opt/anaconda3/envs/MSE446/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Processed 200000 rows
Processed 400000 rows
Processed 600000 rows
Processed 800000 rows
Processed 1000000 rows
Processed 1200000 rows
Processed 1400000 rows
Processed 1600000 rows
Processed 1800000 rows
Processed 2000000 rows
Processed 2200000 rows
Processed 2400000 rows
Processed 2600000 rows
Processed 2800000 rows
Processed 3000000 rows
Processed 3200000 rows
Processed 3400000 rows
Processed 3600000 rows
Processed 3800000 rows
Processed 4000000 rows
Processed 4200000 rows
Processed 4400000 rows
Processed 4600000 rows
Processed 4800000 rows
Processed 5000000 rows
Processed 5200000 rows
Processed 5400000 rows
Processed 5600000 rows
Processed 5800000 rows
Processed 6000000 rows
Processed 6200000 rows
Processed 6400000 rows
Processed 6600000 rows
Processed 6800000 rows
Processed 7000000 rows
Processed 7200000 rows
Processed 7400000 rows
Processed 7600000 rows
(7728394, 46)

,ID,Source,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
0,A-1,Source2,3,2016-02-08 05:46:00,2016-02-08 11:00:00,39.865147,-84.058723,NaN,NaN,0.01,...,False,False,False,False,False,False,Night,Night,Night,Night
1,A-2,Source2,2,2016-02-08 06:07:59,2016-02-08 06:37:59,39.928059,-82.831184,NaN,NaN,0.01,...,False,False,False,False,False,False,Night,Night,Night,Day
2,A-3,Source2,2,2016-02-08 06:49:27,2016-02-08 07:19:27,39.063148,-84.032608,NaN,NaN,0.01,...,False,False,False,False,True,False,Night,Night,Day,Day
3,A-4,Source2,3,2016-02-08 07:23:34,2016-02-08 07:53:34,39.747753,-84.205582,NaN,NaN,0.01,...,False,False,False,False,False,False,Night,Day,Day,Day
4,A-5,Source2,2,2016-02-08 07:39:07,2016-02-08 08:09:07,39.627781,-84.188354,NaN,NaN,0.01,...,False,False,False,False,True,False,Day,Day,Day,Day

In [ ]:
# Finding the top 10 cities with the most accidents
df["City"].value_counts().head(10)

City
Miami          186917
Houston        169609
Los Angeles    156491
Charlotte      138652
Dallas         130939
Orlando        109733
Austin          97359
Raleigh         86079
Nashville       72930
Baton Rouge     71588
Name: count, dtype: int64

In [9]:
# To trim the dataset, we choose the top 3 cities with the most accidents: Miami, Houston, and Los Angeles
df_trimmed = df[df["City"].isin(["Miami", "Houston", "Los Angeles"])]
df_trimmed

,ID,Source,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
42866,A-42867,Source2,2,2016-06-21 10:46:30,2016-06-21 11:27:00,34.078926,-118.289040,NaN,NaN,0.000,...,False,False,False,False,False,False,Day,Day,Day,Day
42867,A-42868,Source2,3,2016-06-21 10:49:21,2016-06-21 11:34:21,34.091179,-118.239471,NaN,NaN,0.000,...,False,False,False,False,False,False,Day,Day,Day,Day
42881,A-42882,Source2,3,2016-06-21 10:51:45,2016-06-21 11:36:45,34.037239,-118.309074,NaN,NaN,0.000,...,False,True,False,False,False,False,Day,Day,Day,Day
42883,A-42884,Source2,3,2016-06-21 10:56:24,2016-06-21 11:34:00,34.027458,-118.274490,NaN,NaN,0.000,...,False,False,False,False,False,False,Day,Day,Day,Day
42898,A-42899,Source2,3,2016-06-21 11:30:46,2016-06-21 12:00:46,33.947544,-118.279434,NaN,NaN,0.000,...,False,False,False,False,False,False,Day,Day,Day,Day
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7728130,A-7777498,Source1,3,2019-08-23 17:32:09,2019-08-23 18:02:03,29.971810,-95.562340,29.96023,-95.546779,1.228,...,False,False,False,False,False,False,Day,Day,Day,Day
7728357,A-7777725,Source1,3,2019-08-23 04:04:48,2019-08-23 04:33:53,34.075790,-118.276680,34.07431,-118.272250,0.273,...,False,False,False,False,False,False,Night,Night,Night,Night
7728361,A-7777729,Source1,2,2019-08-23 12:52:31,2019-08-23 13:20:14,34.023790,-118.276390,34.02576,-118.275290,0.150,...,False,False,False,False,False,False,Day,Day,Day,Day
7728364,A-7777732,Source1,2,2019-08-23 13:42:50,2019-08-23 14:10:06,34.070610,-118.263910,34.06974,-118.261550,0.148,...,False,False,False,False,False,False,Day,Day,Day,Day
7728376,A-7777744,Source1,2,2019-08-23 15:45:43,2019-08-23 16:14:31,34.043650,-118.443730,34.04934,-118.448420,0.476,...,False,False,False,False,False,False,Day,Day,Day,Day