In [3]:
import pandas as pd
final_results = pd.read_parquet('final_results.parquet', engine='fastparquet')

In [9]:
base_features = [
    'Hour', 'Day_of_Week', 'Month', 'Weekend', 'Holiday', 'Year', 'Zone_Int_ID', 'Amenity', 'Crossing', 'Give_Way', 'Junction',
    'Railway', 'Station', 'Stop', 'Traffic_Signal', 'City_Houston', 'City_Miami', 'Temperature(F)', 'Humidity(%)', 'Pressure(in)',
    'Visibility(mi)', 'Wind_Speed(mph)', 'Precipitation(in)', 'Weather_Clear', 'Weather_Cloudy', 'Weather_Dust/Windy',
    'Weather_Rain/Drizzle', 'Weather_Snow/Ice', 'Weather_Stormy', 'Weather_Visibility Issues'
]

engineered_features = [
    'Wind_x_Precip', 'Hour_x_Weekend', 'BadWeather', 'BadWeather_x_Hour', 'Hour_squared', 'WindSpeed_squared', 'Precip_squared',
    'Hour_sin', 'Hour_cos', 'Month_sin', 'Month_cos', 'DayOfWeek_sin', 'DayOfWeek_cos', 'Zone_Mean', 'Zone_Std', 'Zone_Max'
]

features = base_features + engineered_features
print(f"Total features: {len(features)}")

Total features: 46

In [10]:
final_results[features]

,Hour,Day_of_Week,Month,Weekend,Holiday,Year,Zone_Int_ID,Amenity,Crossing,Give_Way,...,Precip_squared,Hour_sin,Hour_cos,Month_sin,Month_cos,DayOfWeek_sin,DayOfWeek_cos,Zone_Mean,Zone_Std,Zone_Max
0,10,2,3,0,0,2022,0,0.034011,0.188304,0.007051,...,0.0,0.500000,-0.866025,1.0,6.123234e-17,0.974928,-0.222521,0.567745,1.064073,9
1,10,2,3,0,0,2022,1,0.021739,0.231121,0.041190,...,0.0,0.500000,-0.866025,1.0,6.123234e-17,0.974928,-0.222521,0.176973,0.501770,7
2,10,2,3,0,0,2022,2,0.000000,0.133127,0.040248,...,0.0,0.500000,-0.866025,1.0,6.123234e-17,0.974928,-0.222521,0.083973,0.332614,6
3,10,2,3,0,0,2022,3,0.000000,0.062893,0.000000,...,0.0,0.500000,-0.866025,1.0,6.123234e-17,0.974928,-0.222521,0.038218,0.221691,4
4,10,2,3,0,0,2022,4,0.000000,0.015075,0.000000,...,0.0,0.500000,-0.866025,1.0,6.123234e-17,0.974928,-0.222521,0.057615,0.263937,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
705307,8,3,3,0,0,2023,153,0.000000,0.000000,0.000000,...,0.0,0.866025,-0.500000,1.0,6.123234e-17,0.433884,-0.900969,0.000000,0.000000,0
705308,8,3,3,0,0,2023,154,0.000000,0.000000,0.000000,...,0.0,0.866025,-0.500000,1.0,6.123234e-17,0.433884,-0.900969,0.000000,0.000000,0
705309,8,3,3,0,0,2023,155,0.000000,0.000000,0.000000,...,0.0,0.866025,-0.500000,1.0,6.123234e-17,0.433884,-0.900969,0.000000,0.000000,0
705310,8,3,3,0,0,2023,156,0.000000,0.000000,0.000000,...,0.0,0.866025,-0.500000,1.0,6.123234e-17,0.433884,-0.900969,0.000000,0.000000,0
705311,8,3,3,0,0,2023,157,0.000000,0.000000,0.000000,...,0.0,0.866025,-0.500000,1.0,6.123234e-17,0.433884,-0.900969,0.000000,0.000000,0

In [12]:
import joblib


classifier = joblib.load('models/xgb_classifier_model.pkl')
regressor = joblib.load('models/xgb_regressor_model.pkl')

In [13]:
classifier_importance = pd.DataFrame({'Feature': features, 'Importance': classifier.feature_importances_})
classifier_importance = classifier_importance.sort_values(by='Importance', ascending=False).head(10)

In [14]:
classifier_importance

           Feature  Importance
44        Zone_Std    0.523208
43       Zone_Mean    0.206938
38        Hour_cos    0.041687
1      Day_of_Week    0.028031
24  Weather_Cloudy    0.021174
5             Year    0.020450
2            Month    0.014283
20  Visibility(mi)    0.013819
0             Hour    0.012384
40       Month_cos    0.011926

In [15]:
regressor_importance = pd.DataFrame({'Feature': features, 'Importance': regressor.feature_importances_})
regressor_importance = regressor_importance.sort_values(by='Importance', ascending=False).head(10)

In [16]:
regressor_importance

         Feature  Importance
12       Station    0.080130
34  Hour_squared    0.072625
38      Hour_cos    0.061959
5           Year    0.049411
3        Weekend    0.041795
44      Zone_Std    0.041132
0           Hour    0.036759
45      Zone_Max    0.032672
2          Month    0.029784
1    Day_of_Week    0.028957